# This file was generated by GoReleaser. DO NOT EDIT.
class Scraloud < Formula
  desc "Deploy your scrapers to cloud and manage them easily."
  homepage "https://scraloud.com/"
  version "0.1.5"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/scraloud/cli/releases/download/v0.1.5/cli_0.1.5_Darwin_x86_64.tar.gz"
    sha256 "81254229093e7051ba2d78e3cc9a25bc49eb4162c6a7fa0075bf18a045308d50"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/scraloud/cli/releases/download/v0.1.5/cli_0.1.5_Linux_x86_64.tar.gz"
      sha256 "b9c58b435542cbab3842ac62e901b0937741192333f122b59ab10d2aca02649c"
    end
  end
  
  depends_on "git"

  def install
    bin.install "scraloud"
  end

  def caveats; <<~EOS
    Just use scraloud
  EOS
  end

  test do
    system "#{bin}/scraloud"
  end
end
