# This file was generated by GoReleaser. DO NOT EDIT.
class Scraloud < Formula
  desc "Deploy your scrapers to cloud and manage them easily."
  homepage "https://scraloud.com/"
  version "0.1.7"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/scraloud/scraloud/releases/download/v0.1.7/scraloud_0.1.7_Darwin_x86_64.tar.gz"
    sha256 "b418ee5e1f82b8673353fff8f95ae1a1068004a14f7e13a24f971868e8cd83c3"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/scraloud/scraloud/releases/download/v0.1.7/scraloud_0.1.7_Linux_x86_64.tar.gz"
      sha256 "1ec4c1d74ff06ef1b5ce1266470357f51e32ceb9bb668d70400ffcc3da8bbc72"
    end
  end
  
  depends_on "git"

  def install
    bin.install "scraloud"
  end

  def caveats; <<~EOS
    Just use scraloud
  EOS
  end

  test do
    system "#{bin}/scraloud"
  end
end
